"""Reading notes authored for this conversation's agreed 20-paper corpus.

Dates are arXiv v1 UTC dates. Interpretation and proposed experiments are
editorial teaching material, not claims of independent reproduction.
"""
PAPERS = [
dict(key='saycan', name='SayCan', date='2022-04-04', arxiv='2204.01691', title='Do As I Can, Not As I Say: Grounding Language in Robotic Affordances', topic='可执行性', chapter='foundations',
 problem='语言上合理的下一步，可能超出机器人在当前状态下的能力。',
 mechanism='结合语言模型对技能与任务的相关性判断，以及技能价值函数提供的可执行性信息，在已有技能中选择下一步。关键是把语义知识与具身能力同时纳入决策。',
 evidence='对照仅使用语言信息与加入可执行性信息的设置，检查技能集合是否固定、价值函数从何而来，以及失败发生在选择还是执行阶段。',
 boundary='技能库与价值估计的质量限制了可选行为；高层选对技能不保证低层执行成功。',
 question='如果两项技能的语言相关性相同，但成功概率依赖物体位置，排序应如何随观测变化？',
 connection='与 Inner Monologue 对照：前者突出“选择前是否做得到”，后者突出“执行后如何修正”。'),
dict(key='inner-monologue', name='Inner Monologue', date='2022-07-12', arxiv='2207.05608', title='Inner Monologue: Embodied Reasoning through Planning with Language Models', topic='闭环反馈', chapter='foundations',
 problem='一次生成的计划无法处理执行失败、环境变化和新信息。',
 mechanism='将成功检测、场景描述和人类反馈等信息转成语言，放回规划上下文，让模型在任务过程中调整后续行为。',
 evidence='比较不同反馈来源的贡献，注意成功检测器与场景描述器的来源；区分闭环规划改善与底层技能改变。',
 boundary='反馈也可能错误。规划器能使用反馈，不代表它能识别所有错误反馈。',
 question='如果检测器把抓空报告成成功，闭环系统会在哪一步暴露问题？',
 connection='先读 SayCan，再用本文思考规划循环。后面的验证、恢复与记忆都依赖这条反馈通道。'),
dict(key='cap', name='Code as Policies', date='2022-09-16', arxiv='2209.07753', title='Code as Policies: Language Model Programs for Embodied Control', topic='程序作为策略', chapter='grounding',
 problem='固定技能菜单限制了组合方式，自然语言计划又不能直接驱动物理执行。',
 mechanism='利用代码模型生成可执行程序，组合感知接口、控制原语、几何计算与控制流；通过层次化代码生成递归定义需要的函数。',
 evidence='追踪一个完整例子：模型实际生成哪些代码，哪些感知与运动能力已经由 API 提供？阅读时把这些边界画出来。',
 boundary='程序可执行与任务可完成是不同层面的判断；接口抽象包含了设计者提供的能力。',
 question='把 pick(object) 换成末端位姿与夹爪控制，模型需要补上哪些推理？',
 connection='ProgPrompt 关注程序化提示；CaP-X 进一步系统比较抽象层级和交互条件。'),
dict(key='progprompt', name='ProgPrompt', date='2022-09-22', arxiv='2209.11302', title='ProgPrompt: Generating Situated Robot Task Plans using Large Language Models', topic='情境化规划', chapter='grounding',
 problem='模型可能生成当前环境没有的物体，或当前机器人不能执行的动作。',
 mechanism='将环境中的对象、可用动作和示例计划组织成程序式提示，使计划生成受到具体场景与能力描述的约束。',
 evidence='查看提示结构与生成约束的消融，并区分 VirtualHome 中的结果与真实机械臂的实验条件。',
 boundary='提示中的环境描述必须与执行时状态对应；一种程序格式本身不会解决感知错误。',
 question='移除示例程序或提供过期对象列表，分别破坏了什么能力？',
 connection='与 Code as Policies 并读，比较“用程序表达规划问题”与“生成更丰富的控制程序”。'),
dict(key='voyager', name='Voyager', date='2023-05-25', arxiv='2305.16291', title='Voyager: An Open-Ended Embodied Agent with Large Language Models', topic='持续技能积累', chapter='learning',
 problem='每个任务从头生成行为，无法充分利用先前探索中学到的技能。',
 mechanism='在 Minecraft 中结合自动课程、可执行代码技能库，以及利用环境反馈与错误信息的程序改进循环，让技能逐步积累并被检索复用。',
 evidence='分别检查探索覆盖、技能复用和新任务迁移，阅读自动课程与技能库消融，确认贡献来自哪一个组件。',
 boundary='实验发生在 Minecraft；不能据此推断真实机器人的接触操作与传感器鲁棒性。',
 question='如果随机检索技能也有收益，如何证明语义检索本身起作用？',
 connection='为理解 Playful 和 ASPIRE 的经验积累机制提供概念参照；这种教学联系不等同于宣称直接继承。'),
dict(key='voxposer', name='VoxPoser', date='2023-07-12', arxiv='2307.05973', title='VoxPoser: Composable 3D Value Maps for Robotic Manipulation with Language Models', topic='三维价值图', chapter='grounding',
 problem='高层语言知识与连续的末端运动之间，仍缺少可供运动规划使用的表示。',
 mechanism='借助语言模型的代码生成和视觉语言模型，将目标与约束组合成三维价值图，再由基于模型的规划方法产生闭环轨迹。',
 evidence='选一个任务，找出目标图、避障或约束信息、视觉定位与轨迹规划各自负责的部分，再看扰动实验检验哪一层。',
 boundary='几何目标依赖感知与坐标关系；一张合理的空间价值图并不自动提供所有接触动力学能力。',
 question='“从把手处拉开”需要哪些空间关系？哪些信息仅靠物体类别名称无法确定？',
 connection='与 ReKep 对照：二者都在语言与运动之间引入结构化表示，但表示与求解方式不同。'),
dict(key='sayplan', name='SayPlan', date='2023-07-12', arxiv='2307.06135', title='SayPlan: Grounding Large Language Models using 3D Scene Graphs for Scalable Robot Task Planning', topic='场景表示', chapter='grounding',
 problem='多楼层、多房间的环境规模增加后，把所有状态直接塞进上下文难以有效规划。',
 mechanism='用分层三维场景图进行任务相关的语义搜索，结合经典路径规划，并利用场景图模拟器的反馈迭代修正计划。',
 evidence='检查场景图如何获得与更新、哪些搜索由语言模型完成，以及规划可执行性由何种反馈检验。',
 boundary='环境表示的完整性和更新机制仍然重要；场景图中的可执行不等于所有真实操作都能可靠完成。',
 question='房间关系正确，但杯子位置已经变化，系统应更新哪个层次的状态？',
 connection='为长程移动操作补上状态表示这一维度，与桌面几何操作论文共同阅读。'),
dict(key='rt2', name='RT-2', date='2023-07-28', arxiv='2307.15818', title='RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control', topic='VLA 背景', chapter='policies',
 problem='语言和视觉预训练知识怎样转移到实际机器人动作生成？',
 mechanism='将机器人动作表示成模型可生成的 token，联合机器人轨迹与视觉语言任务进行训练，使视觉语言模型直接参与动作预测。',
 evidence='区分新物体、语义指令与不同泛化设置，查看数据混合方式和动作表示，不只看代表性视频。',
 boundary='动作生成模型的能力与训练分布有关；单个策略的成功不能替代完整系统中的验证和恢复。',
 question='模型能理解一个新语义概念，是否意味着它能执行与该概念相关的全新接触动作？',
 connection='理解 Harness VLA 前的背景之一：先认识被调用策略，再讨论怎样编排它。'),
dict(key='robocodex', name='RoboCodeX', date='2024-02-25', arxiv='2402.16117', title='RoboCodeX: Multimodal Code Generation for Robotic Behavior Synthesis', topic='多模态代码生成', chapter='grounding',
 problem='多模态语义理解需要进一步转化为带物理约束的具体机器人行为。',
 mechanism='采用树状多模态代码生成，将高层指令分解成面向对象的操作单元，并结合专门的数据、预训练与迭代更新的监督微调。',
 evidence='分别记录数据、训练和推理框架的贡献，比较时确认基线得到的感知输入、训练数据与工具接口。',
 boundary='训练代码生成模型与仅在外部增加推理循环是不同的干预，资源与数据条件应分别计算。',
 question='如果保留相同树状框架，只换回未微调模型，哪些能力应该下降？',
 connection='与 CaP 对照模型与系统层面的改进，再与 CaP-X 对照测试时交互的作用。'),
dict(key='rekep', name='ReKep', date='2024-09-03', arxiv='2409.01652', title='ReKep: Spatio-Temporal Reasoning of Relational Keypoint Constraints for Robotic Manipulation', topic='关键点约束', chapter='grounding',
 problem='如何把复杂操作要求表达成既可从视觉获得、又可优化求解的约束？',
 mechanism='用 Python 函数表达三维关键点之间的关系约束，结合视觉模型和视觉语言模型自动生成表示，再通过分层优化计算末端动作。',
 evidence='跟踪关键点提议、约束生成、在线跟踪与优化的完整流程；分别观察语言推理与几何执行的失败。',
 boundary='关键点误差、约束遗漏与运动可达性都会影响结果，生成出合法约束代码不等于约束正确。',
 question='约束都满足时，任务是否一定成功？请构造一个缺少必要约束的反例。',
 connection='与 VoxPoser 并读，讨论结构化几何表示如何影响可解释性、求解和错误归因。'),
dict(key='pi05', name='π₀.₅', date='2025-04-22', arxiv='2504.16054', title='π₀.₅: a Vision-Language-Action Model with Open-World Generalization', topic='策略泛化', chapter='policies',
 problem='端到端机器人策略怎样在训练场地之外执行实际、长程的操作任务？',
 mechanism='在 π₀ 基础上进行异构任务共同训练，将多机器人数据、网络数据、高层语义预测及低层动作等信息结合，以支持更广的泛化。',
 evidence='关注训练数据覆盖、新环境的定义，以及语义子任务预测与动作能力之间的关系。不要把模型家族不同版本的实验混为一谈。',
 boundary='学习策略的泛化与外部 agent 的重规划是不同机制；二者可能组合，需要分别验证增益。',
 question='换一个家庭场景与换一种动作技能，分别要求哪类泛化？',
 connection='为 AtomicVLA 的技能建模和 Harness VLA 的外部编排提供背景。'),
dict(key='roboos', name='RoboOS', date='2025-05-06', arxiv='2505.03673', title='RoboOS: A Hierarchical Embodied Framework for Cross-Embodiment and Multi-Agent Collaboration', topic='跨本体协作', chapter='systems',
 problem='异构机器人需要共享任务理解与状态，同时调用各自不同的执行能力。',
 mechanism='以分层架构连接高层 RoboBrain、模块化技能库和实时共享记忆，组织长程规划、任务调度与多机器人协作。',
 evidence='读清共享状态、任务分配与技能执行的接口；检查跨本体实验中，哪些适配已经提前完成。',
 boundary='“支持多个本体”不自动等于无需适配地迁移任意技能；同步、通信与控制冲突需要具体机制。',
 question='两个机器人对同一物体位置持有不同观测时，谁能更新共享事实？',
 connection='与 PhyAgentOS 对照系统服务的划分，再与 RoboHarness 对照策略异构性。'),
dict(key='atomicvla', name='AtomicVLA', date='2026-03-08', arxiv='2603.07648', title='AtomicVLA: Unlocking the Potential of Atomic Skill Learning in Robots', topic='参数化技能', chapter='policies',
 problem='整体式动作解码器如何支持更可组合的技能与持续能力扩展？',
 mechanism='联合任务计划、原子技能抽象与细粒度动作，通过技能引导的混合专家和路由机制组织技能专家，并支持新增技能。',
 evidence='检查技能划分、专家路由、长程任务和持续学习实验；注意数据、参数规模和训练预算是否可比。',
 boundary='模型中的技能专家不等同于可独立调用的程序库，两者的更新代价和复用方式不同。',
 question='专家数量增加带来的提升，如何与技能结构本身带来的提升区分？',
 connection='将它与 Voyager、ASPIRE 放在一起，辨认“技能”在不同工作中的实际载体。'),
dict(key='roboclaw', name='RoboClaw', date='2026-03-12', arxiv='2603.11558', title='RoboClaw: An Agentic Framework for Scalable Long-Horizon Robotic Tasks', topic='采集学习执行闭环', chapter='learning',
 problem='人工复位和数据采集成本，使策略学习与长程部署难以持续迭代。',
 mechanism='用同一 VLM 驱动控制器连接数据采集、策略学习和任务执行；用正向操作与逆向恢复组成 Entangled Action Pairs，形成可自复位的采集循环。',
 evidence='同时记录完成率、人工投入、复位成功率和新增数据成本，检查学习与部署阶段的接口一致性。',
 boundary='恢复动作也会失败；自复位的可行性依赖任务与环境，不应直接推广到不可逆操作。',
 question='减少人工时间的收益是否仍成立，如果把失败复位后的接管时间算进去？',
 connection='与 Playful 对照“如何探索”，与 ASPIRE 对照“积累的是策略数据还是修复知识”。'),
dict(key='capx', name='CaP-X', date='2026-03-23', arxiv='2603.22435', title='CaP-X: A Framework for Benchmarking and Improving Coding Agents for Robot Manipulation', topic='能力评测', chapter='evaluation',
 problem='如何区分 coding agent 自身能力与人为提供的控制抽象、感知信息和交互预算？',
 mechanism='通过 CaP-Gym 与 CaP-Bench 改变原语抽象、感知和多轮交互条件，并研究 CaP-Agent0 的测试时机制及 CaP-RL 的训练路径。',
 evidence='先读评测层级，再读分数：是否使用特权状态、原语有多高层、允许多少轮、采用哪些反馈和集成策略？',
 boundary='改变接口或计算预算就改变了比较问题；某一设置的高分不代表跨设置的统一能力排名。',
 question='两种 agent 成功率相同，但一个用了四倍尝试次数，你会如何报告它们？',
 connection='建议在阅读 2026 年系统工作之前读评测部分，用同一张条件表检查后续论文。'),
dict(key='playful', name='Playful Agentic Robot Learning', date='2026-06-17', arxiv='2606.19419', title='Playful Agentic Robot Learning', topic='主动探索', chapter='learning',
 problem='只在收到下游任务后积累经验，会错过任务到来前的自主技能准备。',
 mechanism='RATs 在 play 阶段提出探索任务，编写与执行机器人程序，利用反馈验证、诊断并修复，沉淀代码技能；测试时检索冻结的技能库。',
 evidence='关注与 no-play、random-play 的比较、探索预算、下游任务划分，以及测试时技能库是否保持冻结。',
 boundary='探索有成本，技能库覆盖也可能与下游任务相近；泛化结论需要明确任务与状态的划分。',
 question='在相同探索次数下，课程生成的收益来自覆盖更广，还是恰好更接近测试任务？',
 connection='接在 Voyager 后阅读，并与 ASPIRE 的执行修复和技能积累机制对照。'),
dict(key='aspire', name='ASPIRE', date='2026-06-30', arxiv='2607.00272', title='ASPIRE: Agentic /Skills Discovery for Robotics', topic='修复知识积累', chapter='learning',
 problem='执行失败中的具体经验，怎样持续变成能帮助后续任务的知识？',
 mechanism='结合细粒度多模态执行轨迹、失败诊断、程序修复与验证，将有效经验收入技能库，并用进化搜索扩展候选修复。',
 evidence='区分执行引擎、技能复用与进化搜索的消融；检查跨任务划分、调试预算和仿真到真实机器人的具体实验范围。',
 boundary='论文明确讨论了真实世界自主终身学习的剩余挑战，包括成功检测、复位与安全监控。',
 question='记忆帮助的是同一任务重试，还是从未见过的任务？如何用实验区分？',
 connection='与 Playful 比较技能获取时机，与 Harness VLA 比较“扩展技能知识”和“学会使用固定原语”。'),
dict(key='harness-vla', name='Harness VLA', date='2026-07-09', arxiv='2607.08448', title='Harness VLA: Steering Frozen VLAs into Reliable Manipulation Primitives via Memory-Guided Agents', topic='冻结策略编排', chapter='policies',
 problem='具备局部接触能力的 VLA，在语义、布局和任务变化下可能无法完成整段轨迹。',
 mechanism='将冻结 VLA 暴露成可重试的接触操作原语，搭配固定的解析原语；利用任务经验和全局规则学习何时调用、如何预定位与失败后重整。',
 evidence='检查冻结策略、解析原语、任务特定记忆和全局记忆各自的贡献；明确探索轨迹与评测种子的关系。',
 boundary='不微调 VLA 不等于不需要先前经验或测试时计算；系统收益应连同这些成本报告。',
 question='如果所有增益都来自更好的初始姿态，怎样解释 memory 模块的必要性？',
 connection='与 RoboHarness 并读，分别研究局部 VLA 调用和更广泛的异构策略交接。'),
dict(key='phyagentos', name='PhyAgentOS', date='2026-07-18', arxiv='2607.16636', title='PhyAgentOS: A Self-Evolving Operating System for Embodied Agents with Decoupled Cognitive Planning and Physical Execution', topic='运行时与验证', chapter='systems',
 problem='规划器、策略和不同设备缺少统一执行单元、共享状态、任务验证与经验服务。',
 mechanism='以 session 为调度与验证单元，通过文件化状态协议解耦认知与执行，并将结果验证、记忆与运行约束组织为系统服务。',
 evidence='追踪一次 session 的状态与证据流，区分接口统一、运行可靠性与具体任务性能的证据。',
 boundary='统一抽象不能消除底层设备差异；跨环境验证需要说明相同与不同的组件。',
 question='一个 session 正常退出但目标没有实现，运行时应该保存什么结果？',
 connection='与 RoboOS 比较系统边界，与 Inner Monologue 对照反馈如何从提示组织走向运行时服务。'),
dict(key='roboharness', name='RoboHarness', date='2026-07-20', arxiv='2607.18060', title='RoboHarness: Memory-Driven Orchestration of Heterogeneous Robot Policies for Long-Horizon Planning', topic='异构策略交接', chapter='policies',
 problem='不同策略各有所长，但前一个策略的结束状态未必适合下一个策略开始。',
 mechanism='将 VLA、RL、TAMP 等控制系统封装为 agentic skills，以执行记忆和在线证据估计能力范围；Memory Bridge 引导机器人进入更适合后续策略的状态区域。',
 evidence='分别检查策略路由与交接机制的消融，记录检索轨迹来源、切换失败和进入适用区域所需的动作成本。',
 boundary='方法依赖能力估计与可达的交接状态；独立策略各自高成功率不保证组合后的长程可靠性。',
 question='加入 bridge 后成功率提升，如何排除只是因为额外动作预算更多？',
 connection='回到 SayCan 的可执行性问题：这里需要判断的还包括策略之间的状态兼容性。'),
]
